### ISSUE TITLE
No-Communication on additional NIC slots

### ISSUE THREAD

**Issue by wed-cu** [VFrontDe-Org/ESXi-Customizer-PS#38]
Hey VFrontDe,
I've additional NICs model Realtek 8168 on my home server,
Cannot recieve any communication with net55 driver.
Only succeed to communicate my network with motherboard NIC.
All NICS are the same model with no diffrences.
Checked the communication by adding all of them as a management interfaces.
Even tried to make seperate vmk NIC with all the other additional NICs and connect them to another network and still have no communication, recieving this output from ESXI 6.7:
sendto() failed (host is down).
My ESXI Version is:
VMware ESXi 6.7.0 Update 3
I've attached a screenshot of all of my NICs:
<img width="926" alt="Nics" src="https://user-images.githubusercontent.com/79047401/107878235-daa2e800-6ed9-11eb-8c80-9c2ba24ae43e.png">
Have you got any suggestions/advices how to solve it?
P.S
I've used ESXi-Customizer-PS to install ESXI 6.7 with net55 driver ( This is the reason i opened the issue subject here) not sure if it installed correctly since only 1 NIC is productive.

**Comment by virtualex-itv** [comment]
This is not an issue with the script, all the script will do is embed the driver into the image so it will automagically get installed with ESXi on the server.  If you checked the generated log file it would show `[OK]` next to that step.

What was the command you executed to create the custom .iso?
