### ISSUE TITLE
The ampersand (&) character is not allowed

### ISSUE THREAD

**Issue by johnkristian** [VFrontDe-Org/ESXi-Customizer-PS#40]
When I try to run the script, I get this:

`PS C:\00\01.esxi\areca> .\ESXi-Customizer-PS.ps1

Security warning
Run only scripts that you trust. While scripts from the internet can be useful, this script can potentially harm your
computer. If you trust this script, use the Unblock-File cmdlet to allow the script to run without this warning
message. Do you want to run C:\00\01.esxi\areca\ESXi-Customizer-PS.ps1?
[D] Do not run  [R] Run once  [S] Suspend  [?] Help (default is "D"): r
At C:\00\01.esxi\areca\ESXi-Customizer-PS.ps1:185 char:23
+                   Sign&nbsp;up
+                       ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quot
ation marks ("&") to pass it as part of a string.
At C:\00\01.esxi\areca\ESXi-Customizer-PS.ps1:213 char:189
+ ... ata-ga-click="(Logged out) Header, go to Features">Features <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
At C:\00\01.esxi\areca\ESXi-Customizer-PS.ps1:213 char:269
+ ... nk-symbol float-right text-normal color-text-tertiary pr-3">&rarr;</s ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quot
ation marks ("&") to pass it as part of a string.
At C:\00\01.esxi\areca\ESXi-Customizer-PS.ps1:215 char:165
+ ... ck Link--secondary no-underline f5 Bump-link--hover">Mobile <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
At C:\00\01.esxi\areca\ESXi-Customizer-PS.ps1:215 char:245
+ ... nk-symbol float-right text-normal color-text-tertiary pr-3">&rarr;</s ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quot
ation marks ("&") to pass it as part of a string.
At C:\00\01.esxi\areca\ESXi-Customizer-PS.ps1:216 char:176
+ ... k Link--secondary no-underline f5 Bump-link--hover">Actions <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
At C:\00\01.esxi\areca\ESXi-Customizer-PS.ps1:216 char:256
+ ... nk-symbol float-right text-normal color-text-tertiary pr-3">&rarr;</s ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quot
ation marks ("&") to pass it as part of a string.
At C:\00\01.esxi\areca\ESXi-Customizer-PS.ps1:217 char:182
+ ... ink--secondary no-underline f5 Bump-link--hover">Codespaces <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
At C:\00\01.esxi\areca\ESXi-Customizer-PS.ps1:217 char:262
+ ... nk-symbol float-right text-normal color-text-tertiary pr-3">&rarr;</s ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quot
ation marks ("&") to pass it as part of a string.
At C:\00\01.esxi\areca\ESXi-Customizer-PS.ps1:218 char:178
+ ...  Link--secondary no-underline f5 Bump-link--hover">Packages <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : AmpersandNotAllowed

PS C:\00\01.esxi\areca>`

**Comment by virtualex-itv** [comment]
this doesn't seem right, nor can I reproduce this.  Are you running powercli in PowerShell as an administrator?  Also, have you modified the PowerShell execution policy?
