### ISSUE TITLE
Error on get esxi 6.7 .iso

### ISSUE THREAD

**Issue by Proger116** [VFrontDe-Org/ESXi-Customizer-PS#53]
Error while get esxi 6.7 .iso (only 6.7, all others OK):
-command "./ESXi-Customizer-PS-v2.9.0.ps1 -v67 -nsc"
-ozip work well

Log:
TerminatingError(Export-EsxImageProfile): "Error retrieving file for VIB 'VMware_bootbank_esx-ui_1.43.10-20199807': ('<http.client.HTTPResponse object at 0x0000027688DFC248>', "Error opening file object for VIB 'VMware_bootbank_esx-ui_1.43.10-20199807': Expected value '[]' for attribute 'swplatforms', but found value '[<vmware.esximage.Vib.SoftwarePlatform object at 0x00000276890D8848>, <vmware.esximage.Vib.SoftwarePlatform object at 0x00000276890D8648>]'.")."

An unexpected error occurred:
Error retrieving file for VIB 'VMware_bootbank_esx-ui_1.43.10-20199807': ('<http.client.HTTPResponse object at 0x0000027688DFC248>', "Error opening file object for VIB 'VMware_bootbank_esx-ui_1.43.10-20199807': Expected value '[]' for attribute 'swplatforms', but found value '[<vmware.esximage.Vib.SoftwarePlatform object at 0x00000276890D8848>, <vmware.esximage.Vib.SoftwarePlatform object at 0x00000276890D8648>]'.").

**Comment by virtualex-itv** [comment]
[see here](https://github.com/VFrontDe-Org/ESXi-Customizer-PS/issues/49#issuecomment-1279473672)...
